// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFHxlfbharO3PRvaLtkNn3l4Htac8sSY',
    appId: '1:861154114146:web:b0d23c5972453daae3af3b',
    messagingSenderId: '861154114146',
    projectId: 'wassilni-7c51f',
    authDomain: 'wassilni-7c51f.firebaseapp.com',
    storageBucket: 'wassilni-7c51f.firebasestorage.app',
    measurementId: 'G-E98FT8009K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJwpKe3akyRJfnPKy0Zclb7P0toRAkHo',
    appId: '1:861154114146:android:1f66e9feb0689a1de3af3b',
    messagingSenderId: '861154114146',
    projectId: 'wassilni-7c51f',
    storageBucket: 'wassilni-7c51f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADpfJZxQ1mtF6tpzmhVXeAcoQg1oVIRgU',
    appId: '1:861154114146:ios:864ace68b6f41f6fe3af3b',
    messagingSenderId: '861154114146',
    projectId: 'wassilni-7c51f',
    storageBucket: 'wassilni-7c51f.firebasestorage.app',
    iosBundleId: 'com.example.wassilni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADpfJZxQ1mtF6tpzmhVXeAcoQg1oVIRgU',
    appId: '1:861154114146:ios:864ace68b6f41f6fe3af3b',
    messagingSenderId: '861154114146',
    projectId: 'wassilni-7c51f',
    storageBucket: 'wassilni-7c51f.firebasestorage.app',
    iosBundleId: 'com.example.wassilni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFHxlfbharO3PRvaLtkNn3l4Htac8sSY',
    appId: '1:861154114146:web:1270f31704ebc554e3af3b',
    messagingSenderId: '861154114146',
    projectId: 'wassilni-7c51f',
    authDomain: 'wassilni-7c51f.firebaseapp.com',
    storageBucket: 'wassilni-7c51f.firebasestorage.app',
    measurementId: 'G-9KMGW4W0FH',
  );
}
